### ISSUE TITLE
attempt to call method 'add_flag' (a nil value)

### ISSUE THREAD

**Issue by henriquechehad** [thibaultcha/lua-resty-busted#1]
I'm trying to run the project but it's returning the error:

```
# DBG_NOREADLINE=true busted ./test/specs --coverage
...al/openresty/luajit/share/lua/5.1/busted/modules/cli.lua:111: attempt to call method 'add_flag' (a nil value)
```

**Comment by connormckelvey** [comment]
Same. @henriquechehad are you still running into this?

**Comment by khamin** [comment]
#2 fixes the problem for me

**Comment by saucisson** [comment]
@thibaultcha please, publish a new version of the rock, as the published one has the `add_flag` problem, but not the master branch.

**Comment by Tieske** [comment]
for anyone running into similar issues; here's a self contained solution; https://github.com/lunarmodules/busted/issues/414#issuecomment-792614808

**Comment by thibaultcha** [comment]
This is probably much too late and there may exist better solutions today, but it is done, thanks all.
